### ISSUE TITLE
Add frame rate to schema

### ISSUE THREAD

**Issue by tennismann3000** [AV-EFI/av-efi-schema#36]
As suggested in our metadata management meeting on February 27th, I would like to propose adding the property 'has_frame_rate' for the Item class to the AVefi-schema. Closely following the FiafCore schema, we could add it in this form:

For model_yaml:
 Add Item slot "-has_frame_rate"

```
  has_frame_rate:
    rank: ?
    range: FrameRateEnum
    in_subset:
    - TypeRegistrySubset
    description: >-
      Frame Rate describes the number of frames per second of an item. See also: FIAF Moving Image Cataloguing Manual 3.1.5.12.
```

For vocab_yaml:

```
FrameRateEnum:
    rank: 26
    annotations:
    - pid: 21.T11969/9b576f3e1ddac38b56f8
    in_subset:
    - TypeRegistrySubset
    description: >-
      Frames per second of an item.
    see_also:
    - ?
    permissible_values:
      16fps:
        structured_aliases:
        - literal_form: 16 BPS
          in_language: de
        - literal_form: 16 fps
          in_language: en
        description: >-
          FIAF Moving Image Cataloguing Manual D.7.18
        meaning: fiaf:16fps
      23.98fps:
        structured_aliases:
        - literal_form: 23,98 BPS
          in_language: de
        - literal_form: 23.98 fps
          in_language: en
        description: >-
          FIAF Moving Image Cataloguing Manual D.7.18
        meaning: fiaf:23.98fps
      24fps:
        structured_aliases:
        - literal_form: 24 BPS
          in_language: de
        - literal_form: 24 fps
          in_language: en
        description: >-
          FIAF Moving Image Cataloguing Manual D.7.18
        meaning: fiaf:24fps
      25fps:
        structured_aliases:
        - literal_form: 25 BPS
          in_language: de
        - literal_form: 25 fps
          in_language: en
        description: >-
          FIAF Moving Image Cataloguing Manual D.7.18
        meaning: fiaf:25fps
      30fps:
        structured_aliases:
        - literal_form: 30 BPS
          in_language: de
        - literal_form: 30 fps
          in_language: en
        description: >-
          FIAF Moving Image Cataloguing Manual D.7.18
        meaning: fiaf:30fps
      48fps:
        structured_aliases:
        - literal_form: 48 BPS
          in_language: de
        - literal_form: 48 fps
          in_language: en
        description: >-
          FIAF Moving Image Cataloguing Manual D.7.18
        meaning: fiaf:48fps
      VariableFrameRate:
        structured_aliases:
        - literal_form: variable Bildrate
          in_language: de
        - literal_form: variable frame rate
          in_language: en
        description: >-
          FIAF Moving Image Cataloguing Manual D.7.18
        meaning: fiaf:VariableFrameRate
```
