### ISSUE TITLE
Add Entries to Format and ItemElementType

### ISSUE THREAD

**Issue by tennismann3000** [AV-EFI/av-efi-schema#37]
As proposed in our metadata management meeting on June 12th, here are some additions to the AVefi vocabulary:

Addition to FormatAudioTypeEnum:

```
      16mmMagneticTrack:
        structured_aliases:
        - literal_form: 17,5mm Magnetband
          in_language: de
        - literal_form: 17.5mm magnetic track
          in_language: en
```
Addition to FormatVideoTypeEnum:

```
      Digital8:
        structured_aliases:
        - literal_form: Digital 8
          in_language: default
      DV:
        structured_aliases:
        - literal_form: DV
          in_language: default
      DVCAM:
        structured_aliases:
        - literal_form: DVCAM
          in_language: default
      DVCPro:
        structured_aliases:
        - literal_form: DVCPro
          in_language: default
      DVCPro50:
        structured_aliases:
        - literal_form: DVCPro50
          in_language: default
      HDCAM:
        structured_aliases:
        - literal_form: HDCAM
          in_language: default
      HDV:
        structured_aliases:
        - literal_form: HDV
          in_language: default
      MiniDV:
        structured_aliases:
        - literal_form: MiniDV
          in_language: default
      SVHS:
        structured_aliases:
        - literal_form: S-VHS
          in_language: default
      UMatic:
        structured_aliases:
        - literal_form: U-Matic
          in_language: default
      IMX:
        structured_aliases:
        - literal_form: IMX
          in_language: default
      VHS:
        structured_aliases:
        - literal_form: VHS
          in_language: default
```
Addition to ItemElementType:
```
      DCDM:
        structured_aliases:
        - literal_form: DCDM
          in_language: default
      EditDecisionList:
        structured_aliases:
        - literal_form: Schnittliste
          in_language: de
        - literal_form: Edit Decision List
          in_language: en
      Subtitles:
        structured_aliases:
        - literal_form: Untertitel
          in_language: de
        - literal_form: Subtitles
          in_language: en
```
Addition to FormatDigitalFileTypeEnum:
```
      WebM:
        structured_aliases:
        - literal_form: WebM
          in_language: default
      DV:
        structured_aliases:
        - literal_form: DV
          in_language: default
```
