### ISSUE TITLE
Add Entries to WorkformEnum

### ISSUE THREAD

**Issue by tennismann3000** [AV-EFI/av-efi-schema#38]
Suggestion to add Fiction and Documentary to WorkFormEnum:

```
      Fiction:
        structured_aliases:
        - literal_form: Spielfilm
          in_language: de
        - literal_form: Fiction
          in_language: en
        description: http://d-nb.info/gnd/1286825091

      Documentary:
        structured_aliases:
        - literal_form: Dokumentarfilm
          in_language: de
        - literal_form: Documentary
          in_language: en
        description: http://d-nb.info/gnd/4012653-5
```
